{% set version = '1.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ibd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ibd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ibd/ibd_{{ version }}.tar.gz
  sha256: 59cc4ad01e53e6000482e45a356bd196ffed5e9def9120bcd9eb3a6221f1bb67

build:
  merge_build_host: True  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-car
    - r-emmeans
    - r-lpsolve
    - r-multcomp
  run:
    - r-base
    - r-car
    - r-emmeans
    - r-lpsolve
    - r-multcomp

test:
  commands:
    - $R -e "library('ibd')"           # [not win]
    - "\"%R%\" -e \"library('ibd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ibd
  license: GPL (>= 2)
  summary: 'A collection of several utility functions related to binary incomplete block designs.
    The package contains function to generate A- and D-efficient binary incomplete block
    designs with given numbers of treatments, number of blocks and block size. The package
    also contains function to generate an incomplete block design with specified concurrence
    matrix. There are functions to generate balanced treatment incomplete block designs
    and incomplete block designs for test versus control treatments comparisons with
    specified concurrence matrix. Package also allows performing analysis of variance
    of data and computing estimated marginal means of factors from experiments using
    a connected incomplete block design. Tests of hypothesis of treatment contrasts
    in incomplete block design set up is supported. '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ibd
# Version: 1.5
# Date: 2019-04-24
# Title: Incomplete Block Designs
# Authors@R: c(person("B N", "Mandal", role = c("aut", "cre"), email = "mandal.stat@gmail.com"))
# Author: B N Mandal [aut, cre]
# Maintainer: B N Mandal <mandal.stat@gmail.com>
# Depends: R (>= 3.1.1)
# Imports: lpSolve, car, emmeans, multcomp
# Suggests: multcompView
# Description: A collection of several utility functions related to binary incomplete block designs. The package contains function to generate A- and D-efficient binary incomplete block designs with given numbers of treatments, number of blocks and block size. The package also contains function to generate an incomplete block design with specified concurrence matrix. There are functions to generate balanced treatment incomplete block designs and incomplete block designs for test versus control treatments comparisons with specified concurrence matrix. Package also allows performing analysis of variance of data and computing estimated marginal means of factors from experiments using a connected incomplete block design. Tests of hypothesis of treatment contrasts in incomplete block design set up is supported.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2019-04-24 06:06:05 UTC; b
# Repository: CRAN
# Date/Publication: 2019-04-24 07:10:03 UTC
