{% set version = '1.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ibd
  version: {{ version|replace("-", "_") }}

source:
  fn: ibd_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ibd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ibd/ibd_{{ version }}.tar.gz
  sha256: 78ddef6387ab9aedda70bda359cc11e486106383220755ededa5fae3f5faa59c

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-car
    - r-emmeans
    - r-lpsolve
    - r-multcompview
  run:
    - r-base
    - r-mass
    - r-car
    - r-emmeans
    - r-lpsolve
    - r-multcompview

test:
  commands:
    - $R -e "library('ibd')"           # [not win]
    - "\"%R%\" -e \"library('ibd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ibd
  license: GPL (>= 2)
  summary: 'A collection of several utility functions related to binary incomplete block designs.
    The package contains function to generate A- and D-efficient binary incomplete block
    designs with given numbers of treatments, number of blocks and block size. The package
    also contains function to generate an incomplete block design with specified concurrence
    matrix. There are functions to generate balanced treatment incomplete block designs
    and incomplete block designs for test versus control treatments comparisons with
    specified concurrence matrix. Package also allows performing analysis of variance
    of data and computing estimated marginal means of factors from experiments using
    a connected incomplete block design. Tests of hypothesis of treatment contrasts
    in incomplete block design set up is supported. '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
