appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: cTTWuHidaAZfOdPSh9SFlEGavPOMp5+HG47w3EJPR9i6156pcQurJ3WLs2xddTNl0PgwPgo3KXfTclxKRkHmcKyYU58rOHBFBb+1tWv9cee/FgGfBKYLJALE9F8P1G3WgZ7J9zrzSooaU/BwjNO3qoS/WZRLz9Xjto1+5EC2GPXP9lXUYBZ62PUA0ExnFqqC/xlvWSCFoSSJeRbQJkKLTsoP57Xez+t89jRZkPBZ31uSEgMcNkWUPB8jevny/SfiuIl+w2uMBCTtnbDZMvcBQj1f/B0NWiLSXT4jAMIk5XROAouBluer4kZ3GfWhAGnEWdJTIB5ptu2dLUZDpXx8JdJcYSML9YuqYhzPgEppaG0AL0SzXYHEQYvd0LD35po32CkLy7CJkxBrn/ZM+XopGityLAQXZJ6IP8BfnRyn0sCktUYubr8U+RUcXNALVe1czWOaiobLryROe9AG+RIvJNgWNyd6AOtdygfahuZMd0WUwKyiLpaU39DF9Poz/bYwOaYmu4GFORBeYVxm5YFkHt9hK0X9kVafXNw9d9DPNh8FuH0WgLWKEE4aQVhlv/3MRxsP8/Bhyw+3BWHiVJbiYSjqmns1X+nCCZgXBJ66G9U2vFat1TCbGqGao6um8DV0vyeI5uikMRX7Oaj9Mp28zrOCCwG8bIrXzvoRmueYCgM=}
bot:
  automerge: true
